uicache: Add support for user apps, fix app plugins on >=14.5, proper…
ProcursusTeam/uikittools-ng pull request #55
Opened 2023-01-29 00:20 UTC by opa334

…ly support group containers and containerization flags, improve code

This upstreams the changes from TrollStore to support User apps. I also did a few refactors such as directly linking MobileContainerManager.framework, improving the output of `-i`, added a new option `-s` for specifing that an app on the user partition should be registered as `System` and improved the code (a lot).

2023-01-29 00:25 UTC, CRKatri requested changes
Some initial changes, I'll give a more thorough review later.
Could you document `-s` in the manpage too?

2023-01-29 00:25 UTC, CRKatri commented on uicache.m
> +			printf("Error: Unable to register %s\n", path.fileSystemRepresentation);
Use `fprintf()` and keep it on `stderr`.

2023-01-29 00:25 UTC, CRKatri commented on uicache.m
> +			printf("Error: Unable to unregister %s\n", path.fileSystemRepresentation);
Use `fprintf()` and keep it on `stderr`.

2023-01-29 00:45 UTC, opa334 commented
I unfortunately have no clue how to edit the manpage file. You will need to do it, also remove the caveat at the bottom about uicache not being able to operate on App Store apps.

Here is a description for the -s flag:

When registering an app inside `/var/containers`, it will normally be registered as a user app.
When this flag is set, the app will be registered as a system app, regardless of whether it resides inside `/var/containers` or not.

2023-01-29 02:15 UTC, CRKatri commented
Will this work correctly on iOS 12+?

2023-01-29 07:51 UTC, opa334 commented
I don't see why it wouldn't, can test it

2023-03-12 23:12 UTC, Shaflsharif approved these changes

2023-03-30 01:39 UTC, CRKatri approved these changes

2023-03-30 01:39 UTC, merged